TUNING.RALSEI_M_NIGHTVISION =
    GetModConfigData("RALSEI_M_NIGHTVISION") == true

TUNING.RUSSIAN_LOCALIZATION =
    GetModConfigData("RUSSIAN_LOCALIZATION") == true
TUNING.SCP035_RUSSIAN_LOCALIZATION =
    GetModConfigData("SCP035_RUSSIAN_LOCALIZATION") == true

TUNING.SCP049_RUSSIAN_LOCALIZATION =
    GetModConfigData("SCP049_RUSSIAN_LOCALIZATION") == true

TUNING.SOLDAT_RUSSIAN_LOCALIZATION =
    GetModConfigData("SOLDAT_RUSSIAN_LOCALIZATION") == true
